### ISSUE TITLE
Make use of dependabot groups

### ISSUE THREAD

**Issue by Julian** [bowtie-json-schema/bowtie#1203]
Dependabot (as of a little while ago) supports [grouping updates within the same PR](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups).

We don't make use of them, mostly because I couldn't figure out the syntax, the docs examples don't seem very helpful/realistic.

At very least, we should batch updates to:

* the same implementation harness all together
* Bowtie's own Python requirements all together

**Comment by OptimumCode** [comment]
Hi, @Julian.

Could you please clarify this part
> the same implementation harness all together

Do you mean all the dependencies in one harness (e.g. all dependencies used by kotlin-json-schema-validator) or do you mean something else?

**Comment by Julian** [comment]
Yeah basically that!

It's easiest to demonstrate with Corvus.JSONSchema where the harness has 5 or 6 dependencies -- and if you look at the closed pull requests you'll see dependabot sends 6 at a time, but that's ridiculous, we'd never merge one without merging all.

**Comment by OptimumCode** [comment]
Hi, @Julian. I checked implementations for the dependencies that should be updated together. I have found only 2 implementations:

1. **implementations/dotnet-corvus-jsonschema**
    `Corvus\.Json\..*` - 6 dependencies with the same version
    `Microsoft\.Extensions\..*`  - 2 dependencies with the same version
2. **implementations/rust-jsonschema**
    `serde.*` - 2 dependencies with the same version
    _I am not sure here but probably only **serde_json = "1.0"** can be left in Cargo.toml because Serialize and Deserialize traits are not used (like in rust-boon)_

Please, correct me if I missed something.
Creating groups only for those dependencies should solve the problem you mentioned before.

However, if you would like to group all updates for a single implementation harness it might make the dependabot.yml file a bit large... It already has 300 lines and adding groups for all dependencies for each harness will make it much bigger. If you are okay with that I could take a look at it and add groups for all implementations.

Otherwise, I would add groups only for **bowtie** itself, **dotnet-corvus-jsonschema** and **rust-jsonschema** (if `serde` cannot be removed)

P.S.: I noticed that dependabot.yml file has many blocks for docker files (for each implementation). I am not sure if this is a good idea but maybe we could group all docker files in a single directory by creating symlinks to the original files (e.g _Dockerfile_rust_jsonschema -> implementations/rust-jsonschema/Dockerfile_). Dependabot should support multiple docker files (support was added [here](https://github.com/dependabot/dependabot-core/compare/v0.67.1...v0.67.2)). That should significantly reduce the size of the dependabot.yml but will make the process of adding a new implementation a bit more complicated.

**Comment by Julian** [comment]
> Otherwise, I would add groups only for bowtie itself, dotnet-corvus-jsonschema and rust-jsonschema (if serde cannot be removed)

OK let's start with these 3 -- as you note they're where most of the noise comes from (in fact dependabot typically confuses itself mostly when sending PRs for Bowtie's own frontend deps!)

> P.S.: I noticed that dependabot.yml file has many blocks for docker files (for each implementation). I am not sure if this is a good idea but maybe we could group all docker files in a single directory by creating symlinks to the original files (e.g Dockerfile_rust_jsonschema -> implementations/rust-jsonschema/Dockerfile). 

This is possibly worth considering but I actually would like to fully think through whether we want to use Dockerfiles at all, as opposed to some other Buildkit mechanism (#903) which may actually make some of this obsolete! But it's a bit low priority at the minute honestly as what we have is indeed slightly cumbersome but yet works fairly well I think!

And thanks as usual!

**Comment by OptimumCode** [comment]
> in fact dependabot typically confuses itself mostly when sending PRs for Bowtie's own frontend deps!

Do you mean cases when it creates a group of PRs, one of them gets auto-merged and others can't be auto-merged?

**Comment by OptimumCode** [comment]
Got it. In this case, there is no point in creating multiple dependencies groups for the frontend - just a single group that includes all dependencies (the same for bowtie python dependencies, I think). What do you think about that?

**Comment by OptimumCode** [comment]
But in this case, if I understand rules specified [here](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups):

>When a scheduled update runs, Dependabot will refresh pull requests for grouped updates using the following rules:
> * If all the same dependencies need to be updated to the same versions, Dependabot will rebase the branch.
> * If all the same dependencies need to be updated, but a newer version has become available for one (or more) of the dependencies, Dependabot will close the pull request and create a new one.
> * If the dependencies to be updated have changed - for example, if another dependency in the group now has an update available - Dependabot will close the pull request and create a new one.

If a new dependency is updated while the existing PR is not merged Dependabot will close the existing PR and open a new one. The bigger group the more often this can happen

**Comment by Julian** [comment]
> Got it. In this case, there is no point in creating multiple dependencies groups for the frontend - just a single group that includes all dependencies (the same for bowtie python dependencies, I think). What do you think about that?

Sounds good to me I think.

> If a new dependency is updated while the existing PR is not merged Dependabot will close the existing PR and open a new one. The bigger group the more often this can happen

I suspect given the automerge that it's hopefully unlikely they'll stay open very long, so hopefully we're ok there.

**Comment by OptimumCode** [comment]
Okay, let's give it a try then)
