### ISSUE TITLE
Allow running benchmarks over the JSON Schema test suite

### ISSUE THREAD

**Issue by sudo-jarvis** [bowtie-json-schema/bowtie#1269]

**Comment by jdesrosiers** [comment]
I just want to point out that I think the test suite would make a terrible benchmark because its schemas are so unrealistic of real world schemas. It would tell us how an implementation performs with very small schemas that do only one thing against very small instances. Those results wouldn't necessarily translate to the performance given large, complex schemas and/or large instances.

That said, I recognize that a more representative benchmark doesn't exist. I personally use the test suite as a benchmark for my own implementation, but only because it's all I have.

**Comment by sudo-jarvis** [comment]
Added support for this in #1370.
