### ISSUE TITLE
Consider some way of indicating implementations which don't support a dialect on the dialect report page

### ISSUE THREAD

**Issue by Julian** [bowtie-json-schema/bowtie#510]
Even though we obviously cannot report on dialects that an implementation doesn't support, it still may be nice to show a hint that other implementations exist for a dialect.

In other words, if someone goes to the draft 7 page and looks at Python implementations and sees 2 of them, it may be nice if there was a subtle indication that "hey there's a third implementation, though it doesn't support this version", perhaps hidden behind a collapsable element saying "Other Implementations" which appears expandable below the summary table.

**Comment by adwait-godbole** [comment]
hey @Julian the solution to this is not straightforward because for e.g. if you are on draft 7 then the web page gets the data from draft7.json file which only contains the implementations info that support draft 7 but now to go looking for other implementations which are not supported by draft 7 we would have to request for all other draft json files like 2020-12, 4, 6, etc.

I am not sure what a better approach would be but perhaps one of it could be to keep a field called unsupported_implementations on every json file ?

**Comment by Julian** [comment]
Having some additional indices (extra JSON files with queries we want to run) has been considered for some other things -- that's definitely reasonable sounding to me (to emit one with data on all implementations in order to solve this)!

Though we have a relatively small amount of dialects and can lazily provide this hint only when we have an answer, so it's also seemingly reasonable to just do the multiple requests you've mentioned -- but you're right that pre-building such a lookup file would be better and not difficult!

**Comment by Julian** [comment]
Let's try something similar to your way but using [`bowtie info`](https://docs.bowtie.report/en/stable/cli/#bowtie-info):

* Add a new file called `implementations.json` which we should rebuild each time we rebuild the UI in GitHub actions. It will be something like `bowtie info $(ls implementations/ | sed 's/^/-i /') --format json` to do this for all implementations, you'll see the existing workflow does this to run the test suite.
* Use that file to know what dialects all known implementations support, and to implement this functionality

Does that make sense?

**Comment by adwait-godbole** [comment]
Yeah @Julian I will make the PR asap. Thanks!.
