### ISSUE TITLE
running bowtie in its native python instance

### ISSUE THREAD

**Issue by tonyfast** [bowtie-json-schema/bowtie#78]
cool project @Julian . i'm working on implementation of json schema as python types. i've had to implement tests similar to what `bowtie` does. i;d rather use a common tool that a home rolled one. 

personally, i'm not a docker/podman user, i suffer enough with conda and pip. would there be anyone to overload/modify/hack the current machinery to run the tests from `bowtie`s python instance?

**Comment by Julian** [comment]
Thanks for the kind words!

Mmm -- not sure I follow the question (possibly the answer is "yes with a small bit of work", but will have to clarify which scenario you're after) -- you want to basically call out to Python-based implementations via Bowtie without that running in separate processes (and separate containers)?

Or something else?

**Comment by tonyfast** [comment]
yes i want to call out to python based implementations with bowtie. i don't want to use docker or podman.

**Comment by Julian** [comment]
Got it -- things aren't set up to do that at the minute, though if you care to help, #19 is the relevant ticket, where the intended change is "instead of assuming every harness gets spun up in a docker container, have some Python PEP 544 protocol which can be used to decide how to get a running implementation", and then in your case you'd have some "trivial" implementation which got to a running implementation just by using the `import` statement.

It's not something I can probably prioritize myself, but if you're interested I'd expect it's doable with a bit of elbow grease.

**Comment by Julian** [comment]
Will close this and we can continue there if you end up being interested!
