### ISSUE TITLE
Details modals for failed tests in the UI should also show the schema + instance for the relevant test

### ISSUE THREAD

**Issue by Julian** [bowtie-json-schema/bowtie#871]
When an implementation fails a test, we show the failed test in a modal which is opened when clicking the details buttons on the dialect report:

![Screenshot 2024-02-13 at 11 56 04](https://github.com/bowtie-json-schema/bowtie/assets/329822/d3185b83-54bd-40d9-b6b5-44b93d0d1d91)

which shows:

![Screenshot 2024-02-13 at 11 56 08](https://github.com/bowtie-json-schema/bowtie/assets/329822/2cdc119d-38c8-43ed-85a7-edae428c0441)

Someone looking at that doesn't have any way of knowing what the contents of that test case are, even though they could go back and find it on the details part of the report. In the screenshotted case, that's:

![Screenshot 2024-02-13 at 11 57 33](https://github.com/bowtie-json-schema/bowtie/assets/329822/c4912e21-2da7-4981-9377-78c12f75759f)

We should make it extremely easy to get from the modal to that information.

The ideal way to handle this would be to have fragments (IDs) associated with each test+implementation, and to have the modal contain a link that jumps directly to the fragment for that test.

An interim solution if that's tricky is to instead simply have an expandable accordion in the modal which shows the same information again.

**Comment by adwait-godbole** [comment]
Working on this!

**Comment by Julian** [comment]
This issue is indeed only about the first part. When we redo the widget, we can redo it both for there and here.

**Comment by Siddharth-Singh-2004** [comment]
@Julian, 

Here's a bit of context: 
Problem statement: Details modal for an implementation needs data about what failed so implementers know what to address:

Solution: I have enhanced the Details modal to show  a specific schema and specific instance of data for a test case, like in part 2 of the solution we outlined above. I took the liberty to a add labels to various pieces of data.

<img width="1637" alt="Screenshot 2024-02-19 at 1 56 05 PM" src="https://github.com/bowtie-json-schema/bowtie/assets/112953828/a669caa8-b53e-4da3-b138-16e441de7cfc">




Ask from you:
Do you want me to add anything else? Once you revert, I'll do the needful.

**Comment by Siddharth-Singh-2004** [comment]
@Julian, Pls let  me know if you have any comments. I'll create a pull request soon after I address those comments.

**Comment by Julian** [comment]
If the issue says:

> The ideal way to handle this would be to have fragments (IDs) associated with each test+implementation, and to have the modal contain a link that jumps directly to the fragment for that test.

Then, miscommunication aside about whether or who was working on it, it's quite odd to ignore [@adwait-godbole's PR](https://github.com/bowtie-json-schema/bowtie/pull/894) which implements that better solution and to ignore it and go down the other less desirable path.

You need to either explicitly say "I think this other way is better for XYZ reasons" or else the right way to handle that is to ask @adwait-godbole whether you can work on top of their commits and fix any issues with them.

**Comment by Siddharth-Singh-2004** [comment]
@Julian, 

Thank you for your comments. I am learning to work with community projects and I did not mean to offend anyone. My understanding of the working is based on reading guidelines on how people are expected to work on community projects. The way I expected this to happen is that for someone to come back on the issue and ask to take over (as seen on some issue threads) or we could have collaborated like you mentioned. I'll keep that in mind for the future.Thank you for the feedback. I appreciate.

Coming to the issue at hand:
Here is why I think the solution I implemented is better:

On the Implementation Details modal, the user is in the context of an implementation, a specific test case, and a specific test underneath that case. What I have displayed above in the modal helps the implementer get to the exact test with instance data  that they need to fix or implement to plug the gap. The user interface I have implemented is better because I have all the data in one place without having to do the back and forth between modal and accordion, which is distracting.

Even if I did the the details modal to the accordion, it still won't get us to the details very quickly. I need to click on each test for my schema and scroll vertically to the schema, place my cursor on a test so instance data populates, and find out the details (3 extra clicks, and 1-2 horizontal scrolls for every failed test). I have to go back and forth between modal and tests to get the bottom of all the errors for a schema.

**As I see it, in my implementation, all errored tests + data is available in one place, which is ideal. The implementer is very productive since they are focussed only on their implementation when they are in the Details Modal.** 

I leave it up to you to decide on the ideal user navigation and let me know how you want us to proceed. 

cc [@adwait-godbole](https://github.com/adwait-godbole)

**Comment by Julian** [comment]
> I am learning to work with community projects and I did not mean to offend anyone.

At least on my part certainly no offense taken, and understood! We're all learning -- hopefully my feedback is never too harsh, just meant to be direct!

> The user interface I have implemented is better because I have all the data in one place without having to do the back and forth between modal and accordion, which is distracting. Even if I did the the details modal to the accordion, it still won't get us to the details very quickly. I need to click on each test for my schema and scroll vertically to the schema, place my cursor on a test so instance data populates, and find out the details (3 extra clicks, and 1-2 horizontal scrolls for every failed test). I have to go back and forth between modal and tests to get the bottom of all the errors for a schema.

This is a very good reason! I think maybe though that we can have both -- a way for someone to see what information they need at a glance, and *also* a way to jump to the "official place where we report on a test". I'm not happy that that official place right now is the accordions on the dialect page, but that's the place right now.

In other words... I agree with your reasoning! But I think we should do both then, have a version appear in the modal which only contains:

* the schema
* the instance
* the specific result for the implementation being looked at

but *also* supports jumping to the "official" accordion so that one can look at other implementations, so one additional "jump to test case" button.

I think that means *combining* Adwait's work with what you've got.

So now one specific piece of feedback for your screenshots / for the modal: I think at very least we should reuse/improve the *schema/instance* widget -- in other words, your reasoning is good, but I think then that we still should not reinvent this component entirely:

![Screenshot 2024-02-20 at 10 04 43 AM](https://github.com/bowtie-json-schema/bowtie/assets/329822/ebd4614a-7985-4235-a346-55557a32b8f3)

we should instead improve it so it works in the modal -- maybe that means supporting horizontal *or* vertical stacking?

**Comment by Siddharth-Singh-2004** [comment]
@Julian,

Thank you for the quick revert. Thanks again for the elaborate note. 

The best way forward based on your comments above, is to split this issue into 3 issues linking back to this one:
Part 1: : Modal to show details of schema and instance, keeping the current look and feel. (my work)
Part 2: Track back from modal to accordion (adwait's work).
Part 3: Refactor schema, instance omponent (currently on the accordion) and have it work when called from accordion or details (and may be potentially a change in the look and feel in details because of stacking, aligning rows or column wise for flex width, and card height, some of which  you mention above).(log a new issue; open for any one to work). 

I'll proceed on this path right away.

@adwait-godbole
